### ISSUE TITLE
Error on use Oracle-to-RedShift-Data-Loader

### ISSUE THREAD

**Issue by PacoVillagrana** [pythorium/Oracle-To-Redshift-Data-Loader#1]
Traceback (most recent call last):
  File "<string>", line 339, in <module>
  File "boto\s3\connection.py", line 503, in get_bucket
  File "boto\s3\connection.py", line 536, in head_bucket
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden

oracle_to_redshift_loader returned -1

The Access is Full to S3 Buckets

How can I solve the problem

**Comment by pythorium** [comment]
Probably typo in credentials. 
If you have standalone script that loads file from the ground into Redshift and you know it 100% works you can use it to test access error.

**Comment by pythorium** [comment]
try this : https://github.com/pythorium/CSV_Loader_For_Redshift

**Comment by PacoVillagrana** [comment]
Thanks...

**Comment by jaiverin** [comment]
Traceback (most recent call last):
  File "<string>", line 346, in <module>
  File "C:\Python27\OracleRedshift\include\extractor.py", line 12, in extract
    cols=get_query_columns('', in_qry)
  File "C:\Python27\OracleRedshift\include\extractor.py", line 104, in get_query
_columns
    p1 = Popen(['echo', 'set serveroutput on echo on termout on feedback off\n%s
' % q], stdout=PIPE,stderr=PIPE)
  File "subprocess.py", line 679, in __init__
  File "subprocess.py", line 893, in _execute_child
WindowsError: [Error 2] El sistema no puede encontrar el archivo especificado
oracle_to_redshift_loader returned -1

executed the oracle_to_redshift_loader.exe
How can I solve the problem

**Comment by pythorium** [comment]
make sure sqlplus.exe is in PATH in windows cmd/CLI

**Comment by jaiverin** [comment]
C:\Python27\OracleRedshift>sqlplus

SQL*Plus: Release 12.1.0.2.0 Production on Mar Abr 3 11:35:25 2018

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Introduzca el nombre de usuario:


set ORACLE_CLIENT_HOME=C:\\app\\NB_JTELLEZ\\product\\12.1.0\\client_1



2018-04-03 11:33 GMT-05:00 pythorium <notifications@github.com>:
